--drop tables
use s7398071


ALTER TABLE Phone
	DROP CONSTRAINT FK_PHONE_COMPANY

ALTER TABLE Equipment
	DROP CONSTRAINT FK_EQUIPMENT_COMPANY

ALTER TABLE Engineer
	DROP CONSTRAINT FK_ENGINEER_COMPANY
	

ALTER TABLE EngSpecialty
	DROP CONSTRAINT FK_ENGSPECIALTY_ENGINEER

ALTER TABLE EngSPecialty
	DROP CONSTRAINT FK_ENGSPECIALTY_SPECIALTY

ALTER TABLE Fault
	DROP CONSTRAINT FK_FAULT_EQUIPMENT


ALTER TABLE EngFault
	DROP CONSTRAINT FK_ENGFAULT_ENGINEER

ALTER TABLE EngFault
	DROP CONSTRAINT FK_ENGFAULT_FAULT

DROP TABLE Company;
DROP TABLE Phone;
DROP TABLE Engineer;
DROP TABLE Equipment;
DROP TABLE Fault;
DROP TABLE Specialty;
DROP TABLE EngSpecialty;
DROP TABLE FaultTYpe;
DROP TABLE EngFault;
	


